### ISSUE TITLE
Mime types configuration

### ISSUE THREAD

**Issue by NielsHamelink-web** [hypersmc/WebServerPlugin#3]
**Describe the solution you'd like**
A `mime_types.yml` config to map specific extensions to specific mime types. This way it's expendable by the user, and the default .yml is easier expendable as well since you do not have an IF-statement hell.

**Missing mime types**
- Images
- PDF/Docx/Excel files

**Comment by hypersmc** [comment]
Hi @NielsHamelink-web,
Yea this would be a neat to implement and easy one too. I will be looking into it quickly as I can.

Thanks

**Comment by hypersmc** [comment]
Hi @NielsHamelink-web,
Would you kindly make this issue in the new [repo](https://github.com/hypersmc/WebPluginV2)?
I will be marking the old repo to archiving.
Thanks!
